apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops4devs-conversao-distancia
  labels:
    app: devops4devs-conversao-distancia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops4devs-conversao-distancia
  template:
    metadata:
      labels:
        app: devops4devs-conversao-distancia
    spec:
      containers:
        - name: devops4devs-conversao-distancia
          image: maycon8609/devops4devs-conversao-distancia:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops4devs-conversao-distancia
spec:
  selector:
    app: devops4devs-conversao-distancia
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort